package com.edenrump.graphic.gpu;

import static org.lwjgl.opengl.GL30.*;

/**
 * This class represents a Vertex Array Object (VertexArrayObject).
 *
 * @author Heiko Brumme
 */

public class VertexArrayObject {

    private final int id;

    /**
     * Static method to create a new VertexArrayObject with an id generated by GL30.glGenVertexArrays()
     */
    public VertexArrayObject() {
        this.id = glGenVertexArrays();
    }

    /**
     * Binds OpenGL to vertex array 0
     */
    public static void unbind() {
        glBindVertexArray(0);
    }

    /**
     * Binds this vao within OpenGL
     */
    public void bind() {
        glBindVertexArray(id);
    }

    /**
     * Getter for the Vertex Array Object ID.
     *
     * @return Handle of the VertexArrayObject
     */
    public int getID() {
        return id;
    }

    /**
     * Method to delete the VAO
     */
    public void delete() {
        glDeleteVertexArrays(id);
    }
}
