package com.edenrump.gpu;

import static org.lwjgl.opengl.GL30.*;

/*
 * Copyright (c) 2020 Ed Eden-Rump
 *     This file is part of Nested Engine.
 *
 *     Nested Engine is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU General Public License as published by
 *     the Free Software Foundation, either version 3 of the License, or
 *     (at your option) any later version.
 *
 *     Nested Engine is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 *
 *     You should have received a copy of the GNU General Public License
 *     along with Nested Engine.  If not, see <https://www.gnu.org/licenses/>.
 *
 *     @Author Ed Eden-Rump
 *
 */

/**
 * This class represents a Vertex Array Object (VertexArrayObject).
 *
 * @author Heiko Brumme
 */

public class VertexArrayObject {

    private final int id;

    /**
     * Static method to create a new VertexArrayObject with an id generated by GL30.glGenVertexArrays()
     */
    public VertexArrayObject() {
        this.id = glGenVertexArrays();
    }

    /**
     * Binds OpenGL to vertex array 0
     */
    public static void unbind() {
        glBindVertexArray(0);
    }

    /**
     * Binds this vao within OpenGL
     */
    public void bind() {
        glBindVertexArray(id);
    }

    /**
     * Getter for the Vertex Array Object ID.
     *
     * @return Handle of the VertexArrayObject
     */
    public int getID() {
        return id;
    }

    /**
     * Method to delete the VAO
     */
    public void delete() {
        glDeleteVertexArrays(id);
    }
}
